name = "event-lister"
compatibility_date = "2026-03-01"

[vars]
# you'll set these in the dashboard for prod; this is optional for local
keep_vars = true

routes = [
  { pattern = "queerwomxnsocial.com/*", zone_name = "queerwomxnsocial.com" }
]